repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        name: upgrade python syntax for newer version
        args: [--py311-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
      - id: django-upgrade
        name: upgrade django project by fixing deprecations
        args: [--target-version, "4.2"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: check code for security issues
        exclude: tests|migrations
  - repo: local
    hooks:
      - id: black
        name: format code with black
        entry: black .
        language: python
        files: \.py$
        exclude: migrations
      - id: isort
        name: sort imports with isort
        entry: isort .
        language: python
        files: \.py$
        exclude: migrations
      - id: flake8
        name: lint code with flake8
        entry: flake8 .
        language: python
        files: \.py$
        exclude: migrations
