language: python
python:
  - "3.9"
os: linux
dist: focal
services:
  - docker
before_install:
  - docker-compose --version
install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - docker-compose --version
  - env > .env.prod
  - docker-compose up -d
  - docker-compose exec -u root web python manage.py migrate --noinput
script:
  - docker-compose exec -u root web pytest -n 2 --cov="." --cov-report=xml
after_success:
  - curl -Os https://uploader.codecov.io/latest/alpine/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
