version: "3.9"

services:
  web:
    env_file:
      - .env.prod
    image: 771499844454.dkr.ecr.eu-central-1.amazonaws.com/skillhunter-ec2-web:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.asgi:application -b 0.0.0.0:8000 -w 8 -k uvicorn.workers.UvicornWorker
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    expose:
      - 8000

  worker:
    env_file:
      - .env.prod
    image: 771499844454.dkr.ecr.eu-central-1.amazonaws.com/skillhunter-ec2-worker:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A core worker --without-heartbeat --without-gossip --without-mingle -l INFO
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - web

  beat:
    env_file:
      - .env.prod
    image: 771499844454.dkr.ecr.eu-central-1.amazonaws.com/skillhunter-ec2-beat:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A core beat -l INFO
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - web

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: on-failure
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  static_volume: null
  media_volume: null
