version: "3.9"

services:

  redis:
    image: redis:7.2-alpine

  rabbitmq:
    image: rabbitmq:3.12-management

  db:
    image: postgres:16.0-alpine
    command: -c max_wal_size=2GB
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - POOL_MODE=transaction
    ports:
      - "5432:5432"
    depends_on:
      - db

  web:
    env_file:
      - .env
    build: .
    command: sh -c "python manage.py collectstatic --no-input --clear && gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker core.asgi:application"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    expose:
      - 8000
    depends_on:
      - redis
      - rabbitmq
      - pgbouncer

  worker:
    env_file:
      - .env
    build: .
    command: celery -A core worker --without-heartbeat --without-gossip --without-mingle -l INFO
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - redis
      - rabbitmq
      - pgbouncer

  beat:
    env_file:
      - .env
    build: .
    command: celery -A core beat -l INFO
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - redis
      - rabbitmq
      - pgbouncer

  nginx:
    build: ./nginx
    restart: on-failure
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgresql_data: null
  static_volume: null
  media_volume: null
