version: "3.8"

services:

  redis:
    image: redis:6-alpine

  db:
    image: postgres:13-alpine
    command: -c max_wal_size=2GB
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  web:
    env_file:
      - .env.prod
    build: .
    command: gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker config.asgi:application
    environment:
      - DJANGO_SECRET_KEY=Sy2COSlhcSUSzw9bDpBCRDs7Pxew9BeVZ8JwrfkqhnWPyIZecx4
      # - ENVIRONMENT=production_or_development
      # - DEBUG=False_or_True
      # - DATABASE_URL=<replace_it_with_your_db_url>
      # - REDIS_URL=<replace_it_with_your_redis_url>
      # - REDIS_PASSWORD=<replace_it_with_your_redis_password>
      # - SENTRY_DSN=<replace_it_with_your_sentry_url>
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: always
    environment:
      - PORT=8000
    volumes:
      - staticfiles_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgresql_data:
  staticfiles_volume:
  media_volume:
