version: "3.9"

services:

  redis:
    image: redis:6-alpine

  db:
    image: postgres:14-alpine
    command: -c max_wal_size=2GB
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  web:
    env_file:
      - .env
    build: .
    environment:
      - PYTHONDEVMODE=1
    command: sh -c "python manage.py collectstatic --no-input --clear && gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker core.asgi:application"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: on-failure
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgresql_data: null
  static_volume: null
  media_volume: null
