version: "3.9"

services:
  web:
    build: .
    command: gunicorn config.asgi:application -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
    environment:
      - "DJANGO_SECRET_KEY=Sy2COSlhcSUSzw9bDpBCRDs7Pxew9BeVZ8JwrfkqhnWPyIZecx4"
      # - "DEBUG=False_or_True"
      # - "ENVIRONMENT=production_or_development"
      # - "DATABASE_URL=<replace_it_with_your_db_url>"
      # - "SENTRY_DSN=<replace_it_with_your_sentry_url>"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:6-alpine

volumes:
  postgres_data:
