# Generated by Django 4.0.2 on 2022-02-03 11:10

import datetime
import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=200)),
                ("created_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Searches",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("clean_name", models.CharField(max_length=50)),
                ("unclean_names", models.TextField()),
                ("created_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["clean_name"],
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("url", models.URLField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("rated_skills", models.TextField()),
                ("created_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                "verbose_name_plural": "Vacancies",
            },
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="search_vector_idx"),
        ),
        migrations.RunSQL(
            sql="""CREATE TRIGGER search_vector_update BEFORE INSERT OR UPDATE
            ON scrapers_vacancy FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'pg_catalog.english', title, content);""",
        ),
        migrations.AlterModelOptions(
            name="search",
            options={"ordering": ["-created_date"], "verbose_name_plural": "Searches"},
        ),
        migrations.RemoveIndex(
            model_name="vacancy",
            name="search_vector_idx",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="search_vector",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="search_vector_idx"),
        ),
        migrations.AlterModelOptions(
            name="search",
            options={"verbose_name_plural": "Searches"},
        ),
        migrations.RemoveIndex(
            model_name="vacancy",
            name="search_vector_idx",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="search_vector",
        ),
        migrations.RunSQL(
            sql="DROP TRIGGER search_vector_update ON scrapers_vacancy;",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="search_vector_idx"),
        ),
        migrations.RunSQL(
            sql="""CREATE TRIGGER search_vector_update BEFORE INSERT OR UPDATE
            ON scrapers_vacancy FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'pg_catalog.english', title);""",
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="created_date",
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 15, 7, 55, 76814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="search",
            name="query",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="search",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="url",
            field=models.URLField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="search",
            name="ip_address",
            field=models.GenericIPAddressField(default="1.1.1.1"),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="search",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelOptions(
            name="search",
            options={"ordering": ["-created_date"], "verbose_name_plural": "Searches"},
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="clean_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
