# Generated by Django 3.0.7 on 2020-06-16 17:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_vector_idx"
            ),
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER search_vector_update BEFORE INSERT OR UPDATE
            ON scrapers_vacancy FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'pg_catalog.english', title, content);
            """,
        ),
    ]
