# Generated by Django 3.0.7 on 2020-06-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_auto_20200618_1603'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vacancy',
            name='search_vector_idx',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='search_vector',
        ),
    ]
