# Generated by Django 3.0.7 on 2020-06-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stopword',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
    ]
