# Generated by Django 3.0.7 on 2020-06-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0004_auto_20200614_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
    ]
