# Generated by Django 3.0.7 on 2020-06-18 16:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0004_auto_20200618_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_idx'),
        ),
    ]
