# Generated by Django 3.0.7 on 2020-06-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0005_auto_20200618_1614"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="search", options={"verbose_name_plural": "Searches"},
        ),
        migrations.RemoveIndex(model_name="vacancy", name="search_vector_idx",),
        migrations.RemoveField(model_name="vacancy", name="search_vector",),
        migrations.RunSQL(
            """
            DROP TRIGGER search_vector_update ON scrapers_vacancy;
            """,
        ),
    ]
