# Generated by Django 3.0.7 on 2020-06-20 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0008_auto_20200619_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
