# Generated by Django 3.0.7 on 2020-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0009_auto_20200620_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='search',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
