# Generated by Django 3.1.2 on 2020-10-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0011_auto_20200710_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='ip_address',
            field=models.GenericIPAddressField(default='1.1.1.1'),
        ),
    ]
