# Generated by Django 3.2.5 on 2021-07-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0013_auto_20210430_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Searches'},
        ),
    ]
