# Generated by Django 3.2.5 on 2021-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0014_alter_search_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='clean_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
