# Generated by Django 4.2.3 on 2023-11-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapers", "0001_squashed_0015_auto_20210714_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="unclean_names",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="rated_skills",
            field=models.JSONField(),
        ),
    ]
